services:
  gateway:
    image: ghcr.io/thesoftwarebakery/plenum
    ports:
      - "6188:6188"
    volumes:
      - ./:/config
    environment:
      - API_KEY=my-secret-key
    command:
      - --config-path=/config
      - --openapi-schema=openapi.yaml
      - --openapi-overlay=overlay-gateway.yaml,overlay-interceptors.yaml
    depends_on:
      - backend

  backend:
    image: wiremock/wiremock:3x
    volumes:
      - ./wiremock:/home/wiremock
